### ISSUE TITLE
PyQt5 __version__ error

### ISSUE THREAD

**Issue by fredrikaverpil** [mottosso/Qt.py#28] opened 2016-05-30 18:47 UTC
I just noticed this when importing PyQt5.

``` python
  File "/usr/local/lib/python2.7/site-packages/Qt.py", line 127, in <module>
    _init()
  File "/usr/local/lib/python2.7/site-packages/Qt.py", line 110, in _init
    sys.modules["Qt"] = available[preferred]()
  File "/usr/local/lib/python2.7/site-packages/Qt.py", line 35, in _pyqt5
    PyQt5.__binding_version__ = PyQt5.__version__
AttributeError: 'module' object has no attribute '__version__'
```

**Comment by mottosso** [comment] 2016-05-30 18:54
I'm not getting that.

```bash
$ python -c "import Qt;print Qt.__binding__"
PyQt5

$ python -c "import Qt;print Qt.__version__"
0.2.0
```

**Comment by fredrikaverpil** [comment] 2016-05-30 19:02
Hm. Is it possible that my version of PyQt5 does not come with the `__version__` attribute?

	❯ python
	Python 2.7.11 (default, Jan 22 2016, 08:29:18)
	[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin
	Type "help", "copyright", "credits" or "license" for more information.
	>>> import PyQt5
	>>> PyQt5.__version__
	Traceback (most recent call last):
	  File "<stdin>", line 1, in <module>
	AttributeError: 'module' object has no attribute '__version__'
	>>> from PyQt5.Qt import PYQT_VERSION_STR
	>>> print PYQT_VERSION_STR
	5.5.1

**Comment by mottosso** [comment] 2016-05-30 19:18
Ah, I see what's going on. I'm using [python-qt5](https://github.com/pyqt/python-qt5) and it's got those attributes.

I'll fix this.

**Comment by chandragupta0001** [comment] 2021-07-15 07:12
i got similar error when using pyinstaller
'''
File "/home/chandragupta/anaconda3/envs/pytorch/lib/python3.8/site-packages/PyInstaller/compat.py", line 632, in importlib_load_source
    return mod_loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 522, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 1027, in load_module
  File "<frozen importlib._bootstrap_external>", line 852, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/chandragupta/anaconda3/envs/pytorch/lib/python3.8/site-packages/PyInstaller/hooks/hook-PyQt5.py", line 11, in <module>
    from PyInstaller.utils.hooks.qt import pyqt5_library_info, \
  File "/home/chandragupta/anaconda3/envs/pytorch/lib/python3.8/site-packages/PyInstaller/utils/hooks/qt.py", line 162, in <module>
    pyqt5_library_info = QtLibraryInfo('PyQt5')
  File "/home/chandragupta/anaconda3/envs/pytorch/lib/python3.8/site-packages/PyInstaller/utils/hooks/qt.py", line 54, in __init__
    if hooks.is_module_satisfies("PyQt5 >= 5.15.4"):
  File "/home/chandragupta/anaconda3/envs/pytorch/lib/python3.8/site-packages/PyInstaller/utils/hooks/__init__.py", line 502, in is_module_satisfies
    version = get_module_attribute(module_name, version_attr)
  File "/home/chandragupta/anaconda3/envs/pytorch/lib/python3.8/site-packages/PyInstaller/utils/hooks/__init__.py", line 352, in get_module_attribute
    raise AttributeError(
AttributeError: Module 'PyQt5' has no attribute '__version__'
'''

**Comment by studentWUR** [comment] 2021-07-15 14:40
@chandragupta0001 I have the same error.  When using the pyinstaller. 

resulted in the AttributeError: Module 'PyQt5' has no attribute 'version'
By installing pip install python-qt5. I did not have this any more in the terminal python:
`
import PyQt5
PyQt5.__version__
`
But the error still existed when using the pyinstaller. Have you found any solution?

**Comment by vrgerardi-ccdc** [comment] 2021-07-15 14:57
I get the same error as well, also when using pyinstaller.

**Comment by Damol22** [comment] 2021-07-15 16:19
@studentWUR @chandragupta0001 

I am also having the issue using pyinstaller via auto-py-to-exe v2.9.0 but not on a computer running v2.7.11. I haven't yet been able to find a fix. Let me know if either of you find a solution.

**Comment by zoccoler** [comment] 2021-07-16 01:15
> @chandragupta0001 I have the same error. When using the pyinstaller.
> 
> resulted in the AttributeError: Module 'PyQt5' has no attribute 'version'
> By installing pip install python-qt5. I did not have this any more in the terminal python:
> `import PyQt5 PyQt5.__version__`
> But the error still existed when using the pyinstaller. Have you found any solution?

Hi all, 
I had the same issue with pyinstaller.
Once I saw this line:
`File "/home/chandragupta/anaconda3/envs/pytorch/lib/python3.8/site-packages/PyInstaller/utils/hooks/qt.py", line 54, in init
if hooks.is_module_satisfies("PyQt5 >= 5.15.4"):`
I was able to proceed with pyinstaller by downgrading PyQt5 to version 5.15.3 with:
`pip install --user PyQt5==5.15.3`

**Comment by Srinivas-Ganti** [comment] 2021-07-16 03:30
> @studentWUR @chandragupta0001
> 
> I am also having the issue using pyinstaller via auto-py-to-exe v2.9.0 but not on a computer running v2.7.11. I haven't yet been able to find a fix. Let me know if either of you find a solution.

Hi @Damol22,
I was having the very same issue this today while trying to package my code with Pyinstaller on a different machine to what i normally use. I checked the versions of several key packages that created this conflict. I downgraded the relevant packages to how I had them on my main machine and it solved the problem. It worked again for me with the following pkg versions and Python upgrade (I use conda and for some reason, the default python for new environments is v3.7.10: for me. So I created a new conda env with python 3.8.8 and installed the following packages and that fixed it for me.


pyqt=5.9.2
qt=5.9.7
pyinstaller=4.3
pyinstaller-hooks-contrib=2020.11
numpy=1.20.1
prompt-toolkit=3.0.17

**Comment by VinACE** [comment] 2021-07-16 17:31
pyqt5=5.9.2

**Comment by danifri** [comment] 2021-07-22 12:07
I had the same issue with pyinstaller.

Fixed it easy with: pip install pyqt5

I think it was just a bug in the version i've had before.
Wished it would be always that easy.

**Comment by Sebbek8** [comment] 2021-07-23 13:55
Hello, I have the same problem. 
Using "pip install pyqt5" did not help for me. 
I also have the latest version.

**Comment by mottosso** [comment] 2021-07-25 09:43
Could this be an issue with pyinstaller? Since it bundles pyqt5 with your application, I fail to see why Qt.py is necessary? Why not call on pyqt5 directly? I’ll reopen this and haven’t taken a closer look yet, but from a glance it appears both unrelated to Qt.py and avoidable by simply not using it.

**Comment by Srinivas-Ganti** [comment] 2021-07-25 09:50
Hi all,

I fixed this issue on my system by making a new anaconda env

Python 3.8.8

With the following pkgs

pyqt=5.9.2
qt=5.9.7
pyinstaller=4.3
pyinstaller-hooks-contrib=2020.11
numpy=1.20.1
prompt-toolkit=3.0.17

**Comment by Sebbek8** [comment] 2021-07-26 08:27
> Hi all,
> 
> I fixed this issue on my system by making a new anaconda env
> 
> Python 3.8.8
> 
> With the following pkgs
> 
> pyqt=5.9.2
> qt=5.9.7
> pyinstaller=4.3
> pyinstaller-hooks-contrib=2020.11
> numpy=1.20.1
> prompt-toolkit=3.0.17

I have tried to create a new anaconda environment with the packages you listed, but that did not work either. Still got the same problem.

Additionally, I tried with an older version of pyinstaller that anaconda uses by default (3.6) which managed to create a .exe file, however, when run, it closed itself straight away. The same happens with pyinstaller version 4.3 as you use.

To take a closer look, i ran the .exe file through a terminal and saw this error message: "ValueError: source code string cannot contain null bytes". 
Not sure how to proceed.

This is the traceback:
```
Traceback (most recent call last):
  File "wind_to_nh3_jupyter.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
  File "matplotlib\pyplot.py", line 43, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
  File "matplotlib\figure.py", line 18, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
  File "matplotlib\projections\__init__.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
ValueError: source code string cannot contain null bytes
[26756] Failed to execute script wind_to_nh3_jupyter
```

**Comment by Srinivas-Ganti** [comment] 2021-07-26 19:34
Seems like pyinstaller is having trouble finding your modules. You could check if pyinstaller works properly on a simple demo app to rule out your installation problems.

If that works try putting this line at the top of your main.py file you are trying to run pyinstaller on..

```
import os
import sys

if getattr(sys, 'frozen, False) and hasattr(sys, '_MEIPASS'):
    os.chdir(sys._MEIPASS)
```

**Comment by mottosso** [comment] 2021-07-26 19:36
Ok, this doesn't appear related to Qt.py and is unrelated to the original issue.

Please confirm this issue only happens with Qt.py, in a demo app such as @Srinivas-Ganti suggested and open a new issue if it cannot be reproduced without Qt.py.

**Closed by mottosso** 2021-07-26 19:36 UTC
Labels: bug
