### ISSUE TITLE
QDesktopServices in Qt.py

### ISSUE THREAD

**Issue by albertosottile** [mottosso/Qt.py#219] opened 2017-07-26 17:23 UTC
I could not find a way to import QDesktopServices using Qt.py . While they were missing in the earlier versions of PySide2, it seems that now they added those under QtGui (see http://code.qt.io/cgit/pyside/pyside.git/tree/PySide2/QtGui/typesystem_gui_common.xml). Also, they are available in PyQt5.QtGui . Would it be possible to update the shim accordingly? Thanks.

**Comment by fredrikaverpil** [comment] 2017-07-27 11:58
I just re-ran build_memberships.py against the PySide2 built against the 5.9 branch. I could make a PR.

```json
{
    "QtQuick": [
        "QQuickAsyncImageProvider", 
        "QQuickFramebufferObject", 
        "QQuickImageProvider", 
        "QQuickImageResponse", 
        "QQuickItem", 
        "QQuickItemGrabResult", 
        "QQuickPaintedItem", 
        "QQuickRenderControl", 
        "QQuickTextDocument", 
        "QQuickTextureFactory", 
        "QQuickTransform", 
        "QQuickView", 
        "QQuickWindow", 
        "QSGAbstractRenderer", 
        "QSGBasicGeometryNode", 
        "QSGClipNode", 
        "QSGDynamicTexture", 
        "QSGEngine", 
        "QSGGeometry", 
        "QSGGeometryNode", 
        "QSGMaterialType", 
        "QSGNode", 
        "QSGOpacityNode", 
        "QSGSimpleRectNode", 
        "QSGSimpleTextureNode", 
        "QSGTexture", 
        "QSGTextureProvider", 
        "QSGTransformNode", 
        "QSharedPointer<QQuickItemGrabResult >"
    ], 
    "QtWebChannel": [
        "QWebChannel", 
        "QWebChannelAbstractTransport"
    ], 
    "QtGui": [
        "QAbstractTextDocumentLayout", 
        "QAccessible", 
        "QAccessibleEvent", 
        "QAccessibleInterface", 
        "QActionEvent", 
        "QBackingStore", 
        "QBitmap", 
        "QBrush", 
        "QClipboard", 
        "QCloseEvent", 
        "QColor", 
        "QConicalGradient", 
        "QContextMenuEvent", 
        "QCursor", 
        "QDesktopServices", 
        "QDoubleValidator", 
        "QDrag", 
        "QDragEnterEvent", 
        "QDragLeaveEvent", 
        "QDragMoveEvent", 
        "QDropEvent", 
        "QEnterEvent", 
        "QExposeEvent", 
        "QFileOpenEvent", 
        "QFocusEvent", 
        "QFont", 
        "QFontDatabase", 
        "QFontInfo", 
        "QFontMetrics", 
        "QFontMetricsF", 
        "QGradient", 
        "QGuiApplication", 
        "QHelpEvent", 
        "QHideEvent", 
        "QHoverEvent", 
        "QIcon", 
        "QIconDragEvent", 
        "QIconEngine", 
        "QImage", 
        "QImageIOHandler", 
        "QImageReader", 
        "QImageWriter", 
        "QInputEvent", 
        "QInputMethodEvent", 
        "QIntValidator", 
        "QKeyEvent", 
        "QKeySequence", 
        "QLinearGradient", 
        "QMatrix", 
        "QMatrix2x2", 
        "QMatrix2x3", 
        "QMatrix2x4", 
        "QMatrix3x2", 
        "QMatrix3x3", 
        "QMatrix3x4", 
        "QMatrix4x2", 
        "QMatrix4x3", 
        "QMatrix4x4", 
        "QMouseEvent", 
        "QMoveEvent", 
        "QMovie", 
        "QOpenGLBuffer", 
        "QOpenGLContext", 
        "QOpenGLFramebufferObject", 
        "QOpenGLShader", 
        "QPageLayout", 
        "QPageSize", 
        "QPagedPaintDevice", 
        "QPaintDevice", 
        "QPaintDeviceWindow", 
        "QPaintEngine", 
        "QPaintEngineState", 
        "QPaintEvent", 
        "QPainter", 
        "QPainterPath", 
        "QPainterPathStroker", 
        "QPalette", 
        "QPdfWriter", 
        "QPen", 
        "QPicture", 
        "QPictureIO", 
        "QPixelFormat", 
        "QPixmap", 
        "QPixmapCache", 
        "QPolygon", 
        "QPolygonF", 
        "QPyTextObject", 
        "QQuaternion", 
        "QRadialGradient", 
        "QRasterWindow", 
        "QRawFont", 
        "QRegExpValidator", 
        "QRegion", 
        "QResizeEvent", 
        "QScreen", 
        "QSessionManager", 
        "QShortcutEvent", 
        "QShowEvent", 
        "QStandardItem", 
        "QStandardItemModel", 
        "QStaticText", 
        "QStatusTipEvent", 
        "QStringListModel", 
        "QStyleHints", 
        "QSurface", 
        "QSurfaceFormat", 
        "QSyntaxHighlighter", 
        "QTabletEvent", 
        "QTextBlock", 
        "QTextBlockFormat", 
        "QTextBlockGroup", 
        "QTextBlockUserData", 
        "QTextCharFormat", 
        "QTextCursor", 
        "QTextDocument", 
        "QTextDocumentFragment", 
        "QTextDocumentWriter", 
        "QTextFormat", 
        "QTextFragment", 
        "QTextFrame", 
        "QTextFrameFormat", 
        "QTextImageFormat", 
        "QTextInlineObject", 
        "QTextItem", 
        "QTextLayout", 
        "QTextLength", 
        "QTextLine", 
        "QTextList", 
        "QTextListFormat", 
        "QTextObject", 
        "QTextObjectInterface", 
        "QTextOption", 
        "QTextTable", 
        "QTextTableCell", 
        "QTextTableCellFormat", 
        "QTextTableFormat", 
        "QToolBarChangeEvent", 
        "QTouchDevice", 
        "QTouchEvent", 
        "QTransform", 
        "QValidator", 
        "QVector2D", 
        "QVector3D", 
        "QVector4D", 
        "QWhatsThisClickedEvent", 
        "QWheelEvent", 
        "QWindow", 
        "QWindowStateChangeEvent", 
        "qAlpha", 
        "qBlue", 
        "qGray", 
        "qGreen", 
        "qIsGray", 
        "qRed", 
        "qRgb", 
        "qRgba"
    ], 
    "QtScript": [
        "QScriptClass", 
        "QScriptClassPropertyIterator", 
        "QScriptContext", 
        "QScriptContextInfo", 
        "QScriptEngine", 
        "QScriptEngineAgent", 
        "QScriptExtensionInterface", 
        "QScriptExtensionPlugin", 
        "QScriptProgram", 
        "QScriptString", 
        "QScriptValue", 
        "QScriptValueIterator", 
        "QScriptable"
    ], 
    "QtXmlPatterns": [
        "QAbstractMessageHandler", 
        "QAbstractUriResolver", 
        "QAbstractXmlNodeModel", 
        "QAbstractXmlReceiver", 
        "QSourceLocation", 
        "QXmlFormatter", 
        "QXmlItem", 
        "QXmlName", 
        "QXmlNamePool", 
        "QXmlNodeModelIndex", 
        "QXmlQuery", 
        "QXmlResultItems", 
        "QXmlSchema", 
        "QXmlSchemaValidator", 
        "QXmlSerializer"
    ], 
    "QtX11Extras": [
        "QX11Info"
    ], 
    "QtQuickWidgets": [
        "QQuickWidget"
    ], 
    "QtWidgets": [
        "QAbstractButton", 
        "QAbstractGraphicsShapeItem", 
        "QAbstractItemDelegate", 
        "QAbstractItemView", 
        "QAbstractScrollArea", 
        "QAbstractSlider", 
        "QAbstractSpinBox", 
        "QAction", 
        "QActionGroup", 
        "QApplication", 
        "QBoxLayout", 
        "QButtonGroup", 
        "QCalendarWidget", 
        "QCheckBox", 
        "QColorDialog", 
        "QColumnView", 
        "QComboBox", 
        "QCommandLinkButton", 
        "QCommonStyle", 
        "QCompleter", 
        "QDataWidgetMapper", 
        "QDateEdit", 
        "QDateTimeEdit", 
        "QDesktopWidget", 
        "QDial", 
        "QDialog", 
        "QDialogButtonBox", 
        "QDirModel", 
        "QDockWidget", 
        "QDoubleSpinBox", 
        "QErrorMessage", 
        "QFileDialog", 
        "QFileIconProvider", 
        "QFileSystemModel", 
        "QFocusFrame", 
        "QFontComboBox", 
        "QFontDialog", 
        "QFormLayout", 
        "QFrame", 
        "QGesture", 
        "QGestureEvent", 
        "QGestureRecognizer", 
        "QGraphicsAnchor", 
        "QGraphicsAnchorLayout", 
        "QGraphicsBlurEffect", 
        "QGraphicsColorizeEffect", 
        "QGraphicsDropShadowEffect", 
        "QGraphicsEffect", 
        "QGraphicsEllipseItem", 
        "QGraphicsGridLayout", 
        "QGraphicsItem", 
        "QGraphicsItemAnimation", 
        "QGraphicsItemGroup", 
        "QGraphicsLayout", 
        "QGraphicsLayoutItem", 
        "QGraphicsLineItem", 
        "QGraphicsLinearLayout", 
        "QGraphicsObject", 
        "QGraphicsOpacityEffect", 
        "QGraphicsPathItem", 
        "QGraphicsPixmapItem", 
        "QGraphicsPolygonItem", 
        "QGraphicsProxyWidget", 
        "QGraphicsRectItem", 
        "QGraphicsRotation", 
        "QGraphicsScale", 
        "QGraphicsScene", 
        "QGraphicsSceneContextMenuEvent", 
        "QGraphicsSceneDragDropEvent", 
        "QGraphicsSceneEvent", 
        "QGraphicsSceneHelpEvent", 
        "QGraphicsSceneHoverEvent", 
        "QGraphicsSceneMouseEvent", 
        "QGraphicsSceneMoveEvent", 
        "QGraphicsSceneResizeEvent", 
        "QGraphicsSceneWheelEvent", 
        "QGraphicsSimpleTextItem", 
        "QGraphicsTextItem", 
        "QGraphicsTransform", 
        "QGraphicsView", 
        "QGraphicsWidget", 
        "QGridLayout", 
        "QGroupBox", 
        "QHBoxLayout", 
        "QHeaderView", 
        "QInputDialog", 
        "QItemDelegate", 
        "QItemEditorCreatorBase", 
        "QItemEditorFactory", 
        "QKeyEventTransition", 
        "QKeySequenceEdit", 
        "QLCDNumber", 
        "QLabel", 
        "QLayout", 
        "QLayoutItem", 
        "QLineEdit", 
        "QListView", 
        "QListWidget", 
        "QListWidgetItem", 
        "QMainWindow", 
        "QMdiArea", 
        "QMdiSubWindow", 
        "QMenu", 
        "QMenuBar", 
        "QMessageBox", 
        "QMouseEventTransition", 
        "QOpenGLWidget", 
        "QPanGesture", 
        "QPinchGesture", 
        "QPlainTextDocumentLayout", 
        "QPlainTextEdit", 
        "QProgressBar", 
        "QProgressDialog", 
        "QPushButton", 
        "QRadioButton", 
        "QRubberBand", 
        "QScrollArea", 
        "QScrollBar", 
        "QShortcut", 
        "QSizeGrip", 
        "QSizePolicy", 
        "QSlider", 
        "QSpacerItem", 
        "QSpinBox", 
        "QSplashScreen", 
        "QSplitter", 
        "QSplitterHandle", 
        "QStackedLayout", 
        "QStackedWidget", 
        "QStatusBar", 
        "QStyle", 
        "QStyleFactory", 
        "QStyleHintReturn", 
        "QStyleHintReturnMask", 
        "QStyleHintReturnVariant", 
        "QStyleOption", 
        "QStyleOptionButton", 
        "QStyleOptionComboBox", 
        "QStyleOptionComplex", 
        "QStyleOptionDockWidget", 
        "QStyleOptionFocusRect", 
        "QStyleOptionFrame", 
        "QStyleOptionGraphicsItem", 
        "QStyleOptionGroupBox", 
        "QStyleOptionHeader", 
        "QStyleOptionMenuItem", 
        "QStyleOptionProgressBar", 
        "QStyleOptionRubberBand", 
        "QStyleOptionSizeGrip", 
        "QStyleOptionSlider", 
        "QStyleOptionSpinBox", 
        "QStyleOptionTab", 
        "QStyleOptionTabBarBase", 
        "QStyleOptionTabWidgetFrame", 
        "QStyleOptionTitleBar", 
        "QStyleOptionToolBar", 
        "QStyleOptionToolBox", 
        "QStyleOptionToolButton", 
        "QStyleOptionViewItem", 
        "QStylePainter", 
        "QStyledItemDelegate", 
        "QSwipeGesture", 
        "QSystemTrayIcon", 
        "QTabBar", 
        "QTabWidget", 
        "QTableView", 
        "QTableWidget", 
        "QTableWidgetItem", 
        "QTableWidgetSelectionRange", 
        "QTapAndHoldGesture", 
        "QTapGesture", 
        "QTextBrowser", 
        "QTextEdit", 
        "QTileRules", 
        "QTimeEdit", 
        "QToolBar", 
        "QToolBox", 
        "QToolButton", 
        "QToolTip", 
        "QTreeView", 
        "QTreeWidget", 
        "QTreeWidgetItem", 
        "QTreeWidgetItemIterator", 
        "QUndoCommand", 
        "QUndoGroup", 
        "QUndoStack", 
        "QUndoView", 
        "QVBoxLayout", 
        "QWhatsThis", 
        "QWidget", 
        "QWidgetAction", 
        "QWidgetItem", 
        "QWizard", 
        "QWizardPage", 
        "qApp"
    ], 
    "QtConcurrent": [
        "QtConcurrent"
    ], 
    "QtTest": [
        "QTest"
    ], 
    "QtQml": [
        "ListProperty", 
        "QJSEngine", 
        "QJSValue", 
        "QJSValueIterator", 
        "QML_HAS_ATTACHED_PROPERTIES", 
        "QQmlAbstractUrlInterceptor", 
        "QQmlApplicationEngine", 
        "QQmlComponent", 
        "QQmlContext", 
        "QQmlDebuggingEnabler", 
        "QQmlEngine", 
        "QQmlError", 
        "QQmlExpression", 
        "QQmlExtensionInterface", 
        "QQmlExtensionPlugin", 
        "QQmlFile", 
        "QQmlFileSelector", 
        "QQmlImageProviderBase", 
        "QQmlIncubationController", 
        "QQmlIncubator", 
        "QQmlListReference", 
        "QQmlNetworkAccessManagerFactory", 
        "QQmlParserStatus", 
        "QQmlProperty", 
        "QQmlPropertyMap", 
        "QQmlPropertyValueSource", 
        "QQmlScriptString", 
        "QQmlTypesExtensionInterface", 
        "VolatileBool", 
        "qmlRegisterType"
    ], 
    "QtNetwork": [
        "QAbstractNetworkCache", 
        "QAbstractSocket", 
        "QAuthenticator", 
        "QHostAddress", 
        "QHostInfo", 
        "QIPv6Address", 
        "QLocalServer", 
        "QLocalSocket", 
        "QNetworkAccessManager", 
        "QNetworkAddressEntry", 
        "QNetworkCacheMetaData", 
        "QNetworkConfiguration", 
        "QNetworkConfigurationManager", 
        "QNetworkCookie", 
        "QNetworkCookieJar", 
        "QNetworkDiskCache", 
        "QNetworkInterface", 
        "QNetworkProxy", 
        "QNetworkProxyFactory", 
        "QNetworkProxyQuery", 
        "QNetworkReply", 
        "QNetworkRequest", 
        "QNetworkSession", 
        "QSsl", 
        "QTcpServer", 
        "QTcpSocket", 
        "QUdpSocket"
    ], 
    "QtWebEngineWidgets": [
        "QWebEngineCertificateError", 
        "QWebEngineDownloadItem", 
        "QWebEngineHistoryItem", 
        "QWebEnginePage", 
        "QWebEngineProfile", 
        "QWebEngineScript", 
        "QWebEngineView"
    ], 
    "QtXml": [
        "QDomAttr", 
        "QDomCDATASection", 
        "QDomCharacterData", 
        "QDomComment", 
        "QDomDocument", 
        "QDomDocumentFragment", 
        "QDomDocumentType", 
        "QDomElement", 
        "QDomEntity", 
        "QDomEntityReference", 
        "QDomImplementation", 
        "QDomNamedNodeMap", 
        "QDomNode", 
        "QDomNodeList", 
        "QDomNotation", 
        "QDomProcessingInstruction", 
        "QDomText", 
        "QXmlAttributes", 
        "QXmlContentHandler", 
        "QXmlDTDHandler", 
        "QXmlDeclHandler", 
        "QXmlDefaultHandler", 
        "QXmlEntityResolver", 
        "QXmlErrorHandler", 
        "QXmlInputSource", 
        "QXmlLexicalHandler", 
        "QXmlLocator", 
        "QXmlNamespaceSupport", 
        "QXmlParseException", 
        "QXmlReader", 
        "QXmlSimpleReader"
    ], 
    "QtHelp": [
        "QHelpContentItem", 
        "QHelpContentModel", 
        "QHelpContentWidget", 
        "QHelpEngine", 
        "QHelpEngineCore", 
        "QHelpIndexModel", 
        "QHelpIndexWidget", 
        "QHelpSearchEngine", 
        "QHelpSearchQuery", 
        "QHelpSearchQueryWidget", 
        "QHelpSearchResultWidget"
    ], 
    "QtScriptTools": [
        "QScriptEngineDebugger"
    ], 
    "QtPrintSupport": [
        "QAbstractPrintDialog", 
        "QPageSetupDialog", 
        "QPrintDialog", 
        "QPrintEngine", 
        "QPrintPreviewDialog", 
        "QPrintPreviewWidget", 
        "QPrinter", 
        "QPrinterInfo"
    ], 
    "QtCore": [
        "ClassInfo", 
        "Connection", 
        "MetaFunction", 
        "Property", 
        "QAbstractAnimation", 
        "QAbstractEventDispatcher", 
        "QAbstractItemModel", 
        "QAbstractListModel", 
        "QAbstractProxyModel", 
        "QAbstractState", 
        "QAbstractTableModel", 
        "QAbstractTransition", 
        "QAnimationGroup", 
        "QBasicMutex", 
        "QBasicTimer", 
        "QBitArray", 
        "QBuffer", 
        "QByteArray", 
        "QByteArrayMatcher", 
        "QChildEvent", 
        "QCollator", 
        "QCollatorSortKey", 
        "QCommandLineOption", 
        "QCommandLineParser", 
        "QCoreApplication", 
        "QCryptographicHash", 
        "QDataStream", 
        "QDate", 
        "QDateTime", 
        "QDir", 
        "QDirIterator", 
        "QDynamicPropertyChangeEvent", 
        "QEasingCurve", 
        "QElapsedTimer", 
        "QEvent", 
        "QEventLoop", 
        "QEventTransition", 
        "QFactoryInterface", 
        "QFile", 
        "QFileDevice", 
        "QFileInfo", 
        "QFileSelector", 
        "QFileSystemWatcher", 
        "QFinalState", 
        "QGenericArgument", 
        "QGenericReturnArgument", 
        "QHistoryState", 
        "QIODevice", 
        "QItemSelection", 
        "QItemSelectionModel", 
        "QItemSelectionRange", 
        "QJsonArray", 
        "QJsonDocument", 
        "QJsonParseError", 
        "QJsonValue", 
        "QLibraryInfo", 
        "QLine", 
        "QLineF", 
        "QLocale", 
        "QMargins", 
        "QMarginsF", 
        "QMessageLogContext", 
        "QMetaClassInfo", 
        "QMetaEnum", 
        "QMetaMethod", 
        "QMetaObject", 
        "QMetaProperty", 
        "QMimeData", 
        "QMimeDatabase", 
        "QMimeType", 
        "QModelIndex", 
        "QMutex", 
        "QMutexLocker", 
        "QObject", 
        "QParallelAnimationGroup", 
        "QPauseAnimation", 
        "QPersistentModelIndex", 
        "QPluginLoader", 
        "QPoint", 
        "QPointF", 
        "QProcess", 
        "QProcessEnvironment", 
        "QPropertyAnimation", 
        "QReadLocker", 
        "QReadWriteLock", 
        "QRect", 
        "QRectF", 
        "QRegExp", 
        "QResource", 
        "QRunnable", 
        "QSaveFile", 
        "QSemaphore", 
        "QSequentialAnimationGroup", 
        "QSettings", 
        "QSignalMapper", 
        "QSignalTransition", 
        "QSize", 
        "QSizeF", 
        "QSocketNotifier", 
        "QSortFilterProxyModel", 
        "QStandardPaths", 
        "QState", 
        "QStateMachine", 
        "QStorageInfo", 
        "QSysInfo", 
        "QSystemSemaphore", 
        "QT_TRANSLATE_NOOP", 
        "QT_TRANSLATE_NOOP3", 
        "QT_TRANSLATE_NOOP_UTF8", 
        "QT_TR_NOOP", 
        "QT_TR_NOOP_UTF8", 
        "QTemporaryDir", 
        "QTemporaryFile", 
        "QTextBoundaryFinder", 
        "QTextCodec", 
        "QTextDecoder", 
        "QTextEncoder", 
        "QTextStream", 
        "QTextStreamManipulator", 
        "QThread", 
        "QThreadPool", 
        "QTime", 
        "QTimeLine", 
        "QTimer", 
        "QTimerEvent", 
        "QTranslator", 
        "QUrl", 
        "QVariantAnimation", 
        "QWaitCondition", 
        "QWriteLocker", 
        "QXmlStreamAttribute", 
        "QXmlStreamAttributes", 
        "QXmlStreamEntityDeclaration", 
        "QXmlStreamEntityResolver", 
        "QXmlStreamNamespaceDeclaration", 
        "QXmlStreamNotationDeclaration", 
        "QXmlStreamReader", 
        "QXmlStreamWriter", 
        "Qt", 
        "QtCriticalMsg", 
        "QtDebugMsg", 
        "QtFatalMsg", 
        "QtInfoMsg", 
        "QtMsgType", 
        "QtSystemMsg", 
        "QtWarningMsg", 
        "SIGNAL", 
        "SLOT", 
        "Signal", 
        "Slot", 
        "qAbs", 
        "qAcos", 
        "qAddPostRoutine", 
        "qAsin", 
        "qAtan", 
        "qAtan2", 
        "qChecksum", 
        "qCritical", 
        "qDebug", 
        "qExp", 
        "qFabs", 
        "qFastCos", 
        "qFastSin", 
        "qFatal", 
        "qFuzzyCompare", 
        "qFuzzyIsNull", 
        "qInstallMessageHandler", 
        "qIsFinite", 
        "qIsInf", 
        "qIsNaN", 
        "qIsNull", 
        "qRegisterResourceData", 
        "qTan", 
        "qUnregisterResourceData", 
        "qVersion", 
        "qWarning", 
        "qrand", 
        "qsrand", 
        "qtTrId"
    ], 
    "QtMultimedia": [
        "QAbstractAudioDeviceInfo", 
        "QAbstractAudioInput", 
        "QAbstractAudioOutput", 
        "QAbstractVideoBuffer", 
        "QAbstractVideoFilter", 
        "QAbstractVideoSurface", 
        "QAudio", 
        "QAudioBuffer", 
        "QAudioDecoder", 
        "QAudioDecoderControl", 
        "QAudioDeviceInfo", 
        "QAudioEncoderSettings", 
        "QAudioEncoderSettingsControl", 
        "QAudioFormat", 
        "QAudioInput", 
        "QAudioInputSelectorControl", 
        "QAudioOutput", 
        "QAudioOutputSelectorControl", 
        "QAudioProbe", 
        "QAudioRecorder", 
        "QAudioRoleControl", 
        "QCamera", 
        "QCameraCaptureBufferFormatControl", 
        "QCameraCaptureDestinationControl", 
        "QCameraControl", 
        "QCameraExposureControl", 
        "QCameraFocusZone", 
        "QCameraImageCapture", 
        "QCameraImageCaptureControl", 
        "QCameraImageProcessingControl", 
        "QCameraInfo", 
        "QCameraInfoControl", 
        "QCameraLocksControl", 
        "QCameraViewfinderSettings", 
        "QCameraViewfinderSettingsControl", 
        "QCameraViewfinderSettingsControl2", 
        "QCameraZoomControl", 
        "QImageEncoderControl", 
        "QImageEncoderSettings", 
        "QMediaAudioProbeControl", 
        "QMediaAvailabilityControl", 
        "QMediaBindableInterface", 
        "QMediaContainerControl", 
        "QMediaContent", 
        "QMediaControl", 
        "QMediaGaplessPlaybackControl", 
        "QMediaNetworkAccessControl", 
        "QMediaObject", 
        "QMediaPlayer", 
        "QMediaPlayerControl", 
        "QMediaPlaylist", 
        "QMediaRecorder", 
        "QMediaRecorderControl", 
        "QMediaResource", 
        "QMediaTimeRange", 
        "QMultimedia", 
        "QRadioData", 
        "QRadioDataControl", 
        "QRadioTuner", 
        "QRadioTunerControl", 
        "QSound", 
        "QSoundEffect", 
        "QVideoDeviceSelectorControl", 
        "QVideoEncoderSettings", 
        "QVideoEncoderSettingsControl", 
        "QVideoFilterRunnable", 
        "QVideoFrame", 
        "QVideoProbe", 
        "QVideoRendererControl", 
        "QVideoSurfaceFormat", 
        "QVideoWindowControl"
    ], 
    "QtMultimediaWidgets": [
        "QCameraViewfinder", 
        "QGraphicsVideoItem", 
        "QVideoWidget", 
        "QVideoWidgetControl"
    ], 
    "QtWebSockets": [
        "QMaskGenerator", 
        "QWebSocket", 
        "QWebSocketCorsAuthenticator", 
        "QWebSocketProtocol", 
        "QWebSocketServer"
    ]
```

**Comment by alby128** [comment] 2017-07-27 14:45
Yeah, at the moment I am struggling in installing PySide2 on macOS 10.12.6 using https://github.com/fredrikaverpil/pyside2-wheels , so I cannot test anything. I need python 2.7, so maybe that is the cause of all problems. I managed to compile everything but python2 from homebrew does not see the new PySide packages, hence Qt.py does not see them. So maybe it is better if you do the PR, thanks.

**Comment by fredrikaverpil** [comment] 2017-07-27 16:49
@alby128 unfortunately, I think you'll have to brew-install the qt5.rb formula that exists in the pyside2-wheels repo. Then you should be able to install and use the wheel. I just recently removed the previous instructions on how to install the wheel on macOS because I also ran into issues when I attempted a simpler install.

**Comment by alby128** [comment] 2017-07-27 18:01
@fredrikaverpil Actually, I just managed to install PySide2, bt linked to the same qt5 (5.9.1) installed by homebrew for PyQt5, thus avoiding all the multiple definition issues caused by having two qt5 installed. I used your build_osx_qt5.6_py2.7.sh script, adapting it for qt5.9, but I had to brew also llvm because I could not find a way to use the clang version included in macOS. Anyway, everything seems ok now. With the latest fix, Qt.py is able to reference to both PySide2 and PyQt5, they are both linked to the same qt5 libraries, and no error message is displayed about definition conflicts. I will experiment a little more with everything in the next few days, but in the meantime it seems that the program I was trying to port from PySide to qt5 now works almost flawlessly. So, thanks for all your help!

**Comment by fredrikaverpil** [comment] 2017-09-25 07:14
@alby128 we revised how we generate the common members used by Qt.py. With PR #234 QDesktopServices will be added to Qt.py, as it was added to PySide2 at some point in time (I haven't dug into when exactly). But you need to be careful to make sure PySide2 on your end uses it, as it may not exist in e.g. older DCC versions.

**Comment by alby128** [comment] 2017-10-02 11:57
@fredrikaverpil I do not understand, are QDesktopServices available in the current version of Qt.py? Thanks

**Comment by fredrikaverpil** [comment] 2017-10-02 13:33
It will be. As soon as #234 is merged.

**Comment by fredrikaverpil** [comment] 2018-05-03 15:18
I believe this was solved. Closing.

**Closed by fredrikaverpil** 2018-05-03 15:18 UTC
Labels: enhancement
